#spring.application.name=ex2
spring:
  application:
    name: ex2

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootdb2
    username: root
    password: 1234
    hikari:
      minimum-idle: 2           # ?? ??? 2?
      maximum-pool-size: 5      # ?? ??? 5?

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
#        use_sql_comments: true # JPQL ?? ??

decorator:
  datasource:
    p6spy:
      enable-logging: true
